	  SUBROUTINE GETPARAM(TOKEN,VALUE,IU)
! G value of TOKEN from file (IU). If no value is found TRIM(VALUE)= ' '
	  IMPLICIT NONE
	  INCLUDE 'mpif.h'
	  INTEGER IPT,NL,IMAX,IU,IEQ,ISHARP,IEXCLAM,ICOM,I1
	  CHARACTER(LEN=300) TOKEN,FILENAME
	  CHARACTER(LEN=300) VALUE,LINE,TOKENT,TEMP
	  LOGICAL EXISTS
	  
	  VALUE='                                             '
          TEMP ='                                             '
	  INQUIRE(IU,EXIST=EXISTS)
	  IF(.NOT.EXISTS) GO TO 41
          REWIND(IU) 
	  TOKENT=ADJUSTL(TOKEN)
	  NL=LEN_TRIM(TOKENT)
	  IF(NL.EQ.0) GO TO 42
	  
	  LINE='                                              '
          IEQ=NL
	  DO WHILE(TOKENT(1:NL).NE.TRIM(LINE(1:NL)))
	    READ(IU,'(A)',ERR=43) LINE
		LINE=ADJUSTL(LINE)
		IEQ=INDEX(LINE,'=')
          ENDDO
          IMAX=LEN_TRIM(LINE)
	  
	  IF(IEQ.LE.NL.OR.IEQ.EQ.IMAX) GO TO 44
          IPT=IEQ+1
	  WRITE(TEMP,'(A)')LINE(IPT:IMAX)
	  TEMP=ADJUSTL(TEMP)
	  ISHARP=INDEX(TEMP,'#')
	  IEXCLAM=INDEX(TEMP,'!')
	  ICOM=MIN(ISHARP,IEXCLAM)
	  I1=MAX(ISHARP,IEXCLAM)
	  IF(ICOM.EQ.0) ICOM=I1
	  IF(ICOM.EQ.1) GO TO 44
	  ICOM=ICOM-1
	  IF(ICOM.LE.0) ICOM=IMAX
	  WRITE(VALUE,'(A)') TEMP(1:ICOM)

	  RETURN
!---------------------errors
41    WRITE(*,'(A,A,A)') 'WARNING: ',TRIM(FILENAME),' NOT FOUND'
      RETURN
42    WRITE(*,'(A,A)') 'FATAL ERROR IN GETINPD: EMPTY TOKEN'
	  STOP
43    WRITE(*,'(A,A)') 'FATAL ERROR: GETINPD FAILS TO READ ',TRIM(FILENAME)
	  STOP
44    WRITE(*,'(4A)') 'FATAL ERROR: INVALID TOKEN FOUND IN ',TRIM(FILENAME),': ',TRIM(LINE)
      STOP
	  END SUBROUTINE GETPARAM
